// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Project = Collections['projects']['schema']['_output']
export declare const projects: Project[]

export type Article = Collections['articles']['schema']['_output']
export declare const articles: Article[]

export type LearningNote = Collections['learningNotes']['schema']['_output']
export declare const learningNotes: LearningNote[]

export type Experiments = Collections['experiments']['schema']['_output']
export declare const experiments: Experiments[]

export type Artifact = Collections['artifacts']['schema']['_output']
export declare const artifacts: Artifact[]

export type Book = Collections['books']['schema']['_output']
export declare const books: Book[]

export type Idea = Collections['ideas']['schema']['_output']
export declare const ideas: Idea[]

export type TimelineEvent = Collections['timelineEvents']['schema']['_output']
export declare const timelineEvents: TimelineEvent[]

export type Topic = Collections['topics']['schema']['_output']
export declare const topics: Topic[]
